language: java

matrix:
  include:
    - env: ADDITIONAL_MAVEN_ARGS="-Pjacoco coveralls:report"

# skip installation step
install: true

cache:
  directories:
    - $HOME/.m2
    -
script:
  - mvn clean verify $ADDITIONAL_MAVEN_ARGS
  -
